# Generated by Django 3.2.4 on 2021-09-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_time', models.DateTimeField(auto_created=True)),
                ('session_id', models.TextField(max_length=100)),
                ('intent', models.TextField(max_length=100)),
                ('action', models.TextField(max_length=100)),
                ('bot_message', models.TextField(max_length=1000)),
                ('client_message', models.TextField(max_length=1000)),
            ],
        ),
    ]
