# Generated by Django 3.2.7 on 2021-09-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('booking_status', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_time', models.CharField(max_length=100)),
                ('intent', models.TextField(max_length=100)),
                ('action', models.TextField(max_length=100)),
                ('bot_message', models.TextField(max_length=1000)),
                ('client_message', models.TextField(max_length=1000)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conversation')),
            ],
        ),
        migrations.DeleteModel(
            name='IntentAction',
        ),
    ]
