# Generated by Django 3.2.7 on 2021-09-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210919_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QA',
            new_name='QApair',
        ),
    ]
