# Generated by Django 3.2.7 on 2021-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_qa_qapair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qapair',
            name='at_time',
        ),
        migrations.AddField(
            model_name='qapair',
            name='create_time_bot_message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qapair',
            name='create_time_client_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
